<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ENT extends Model
{
    use HasFactory;
    protected $table='ENT';
    public  $timestamps = false;
    protected $connection = 'sqlsrv';
    protected $fillable= [
      'ENT_ID',      
      'TIERS',
      'PREFPINO', // prefix piece numero
      'PINO',
      'PIDT',
      'REPR_0001',
      'STATUS',
      'USIMAUTO', 
      'USIM_RESTE',
      'USIM_ACOMPTE',
      'USIM_PLAST',
      'USIM_DATE',
      'PIREF',
      'TIERSRLV', //Tiers relevé
      'TAFAM',//,tarif famille Article
      'TACOD',//Tarif TIERS cod
      'HTMT', //prix hors taxe
      'TTCMT', //prix final
      'HTPDTMT',//Hors Taxes produit
      'REFNB', //Nombre de références 
      //dateTime
      'USERCRDH',
      'USERMODH',
        
    ];
    protected $hidden = [
            'DOS',
           'CE1',
           'CE2',
           'CE3',
           'CE4',
           'CE5',
           'CE6',
           'CE7',
           'CE8',
           'CE9',
           'CEA',
           'CEB',
           'CEC',
           'CED',
           'CEE',
           'CEF',          
           'ETB', 
           'DEV',
           'OP',
           'USERCR',
           'USERMO', 
           'REPR_0002',
           'REPR_0003',
           'RIBCOD',
           'MARCHE',
           'PROJET',
           'DEPO',
           'ADRTIERS_0001',
           'ADRTIERS_0002',
           'ADRTIERS_0003',
           'ADRTIERS_0004',
           'ADRTIERS_0005',
           'ADRCOD_0001',
           'ADRCOD_0002',
           'ADRCOD_0003',
           'ADRCOD_0004',
           'ADRCOD_0005',
           'BLMOD',
           'REGL',
           'TOUR',
        
           'PINOTIERS',
           'TIERSPAYER',
           'TIERSGRP',
           'TIERSRLV',
           'BAPSALCOD',
           'SALCOD',
           'PREFRLVNO',
           'RLVNO',
           'RLVDT',
           'DELDEMDT',
           'DELACCDT',
           'DELREPDT',
           'ECHDT',
           'TAFAM',
           'TAFAMX',
           'REFAM',
           'REFAMX',
           'TACOD',
           'REMCOD',
           'COFAM',
           'COFAMV_0001',
           'COFAMV_0002',
           'COFAMV_0003',
           'AXE_0001',
           'AXE_0002',
           'AXE_0003',
           'AXE_0004',
           'ETANO',
           'TXTEDCODD',
           'TXTEDCODF',
           'CONTACT',
           'PREFBLASNO',
           'BLASNO',
           'BLASDEPO',
           'TPFT',
           'AVENANT',
           'CESINTCOD',
           'PROMOTACOD',
           'PROMOREMCOD',
           'PREFCDNOPERE',
           'CDNOPERE',
           'TPVBL',
           'DEEEINCCOD',
           'PREFPINA',
           'PINA',
           'USERCRDH',
           'USERMODH',
           'CENOTE',
           'NOTE',
           'TXTCODD',
           'TXTCODF',
           'TXTNOTED',
           'TXTNOTEF',
           'ORIGINE',
           'HTMT',
           
           'HTPDTMT',
           'ESCP',
           'ACMT',
           'SOACMT',
           'REMMT',
           'REM1',
           'REMTYP1',
           'FOUHTMT',
           'FOUESCMT',
           'FOUTVAMT',
           'DEVP',
           'PIEDNO_0001',
           'PIEDNO_0002',
           'PIEDNO_0003',
           'PIEDMT_0001',
           'PIEDMT_0002',
           'PIEDMT_0003',
           'NBEX',
           'PIRELCOD',
           'RELCOD',
           'EDITCOD',
           'TRCOD',
           'BOREDICOD',
           'ASCOD',
           'ECHVCOD',
           'ENCASSCOD',
           'ADRTYP_0001',
           'ADRTYP_0002',
           'ADRTYP_0003',
           'ADRTYP_0004',
           'ADRTYP_0005',
           'PRIOCOD',
           'HTCOD',
           'STRES',
           'FAMOD',
           'PERIOD',
           'PORCOD',
           'POICOD',
           'VOLCOD',
           'PORFRFL',
           'POITOT',
           'VOLTOT',
           'COLINB',
           'REFNB',
           'TOURRG',
           'REM_0001',
           'REM_0002',
           'REM_0003',
           'REMTYP_0001',
           'REMTYP_0002',
           'REMTYP_0003',
           'COMP_0001',
           'COMP_0002',
           'COMP_0003',
           'PORTHEOMT',
           'REMPIETOT',
           'TRANSJRNB',
           'OFASCOD',
           'FINAL',
           'QUACOD',
           'CEJOINT',
           'JOINT',
           'DEEEMT',
           'FOUDEEEMT',
           'PRGCDEFLG',
           'BQCPCE',
           'POINCOD',
           'POINTOT',
           'PRIOREG',
           'TVATIE',
           'STLGTGAMCOD',
           'DTFLG',
           'SYNCHROFL',
           'ICPFL',
           'TRANSICOD',
           'TVABLCD3',
           'LIEUINCT',
           'PORFRVAL',
           'PORFRCOD',
           'SITECOD',
           'CEATRAITEFL',
           'BEXNO',
           'BLQFL',
           'BPRELCOD',
           'CATPICOD',
           'CIRCUITVALIDATIONBLFL',
           'CIRCUITVALIDATIONFCTFL',
           'CONDEXP',
           'CONFIRMATIONFL',
           'ETABLNO',
           'FRAISAPPCOD',
           'GOUVFACBLQFL',
           'INDICENO',
           'MODEEXP',
           'MOTIF',
           'PIECEDT',
           'PREFSITNO',
           'REMSEUILFL',
           'SITNO',
           'TAXCPLFFL',
           'TAXSFVFL',
           'TRANSITFL',
           'TVAAUTOLIQFL',
           'UNLOGCOD',
           'UNLOGTOT',
           'UNTYP',
           'VALFINDT',
           'VERSIONDEVISNO',
           'VERSIONDEVISORIPINO',
           'VERSIONDEVISORIPREFPINO',
           'ACOMPTETYP',
           'BPJRNB',
           'PAIEMENTTYP',
           'RESJRNB',
           'STNFL',
           'BIDON',
           'USIM_NOCAM'
            
         //   'BTRETOURFL',
         //   'BTSTATUS',
         //   'BTPINO',
      
    ];
    protected $attributes = [
      'DOS'=>'1',
      'PICOD'=>2,
      'TICOD'=>'C',
      'CE1' =>'A',
      'CE2'=>'  ',
      'CE3'=>'  ',
      'CE4' =>'1',
      'CE5'=>'1',
      'CE6'=>'  ',
      'CE7'=>'  ',
      'CE8'=>' ',
      'CE9'=>'  ',
      'CEA'=>'  ',
      'CEB'=>'  ',
      'CEC'=>'  ',
      'CED'=>'  ',
      'CEE'=>'  ',
      'CEF'=>'  ',         
      'ETB'=>'1',
      'DEV'=>'TND ',
      'OP'=>'C  ',
      'USERCR'=>'DEMO                ',
      'USERMO'=>'DEMO                ', 
      'REPR_0002'=>'                    ',
      'REPR_0003'=>'                    ',
      'RIBCOD'=>'                    ',
      'MARCHE'=>'                    ',
      'PROJET'=>'                    ',
      'DEPO'=>'2  ',
      'ADRTIERS_0001'=>'        ',
      'ADRTIERS_0002'=>'        ',
      'ADRTIERS_0003'=>'        ',
      'ADRTIERS_0004'=>'        ',
      'ADRTIERS_0005'=>'        ',
      'ADRCOD_000        '=>'        ',
      'ADRCOD_0002'=>'        ',
      'ADRCOD_0003'=>'        ',
      'ADRCOD_0004'=>'        ',
      'ADRCOD_0005'=>'        ',
      'BLMOD'=>'        ',
      'REGL'=>'E   ',
      'TOUR'=>'                                        ',
      'PIREF'=>'                                        ',
      'PINOTIERS'=>'                                        ',
      'TIERSPAYER'=>'                                        ',
      'TIERSGRP'=>'                                        ',      
      'BAPSALCOD'=>'                    ',
      'SALCOD'=>'                    ',
      'PREFRLVNO'=>'                    ',     
      'TAFAMX'=>'        ',
      'REFAM'=>'        ',
      'REFAMX'=>'        ',      
      'REMCOD'=>'        ',
      'COFAM'=>'        ',
      'COFAMV_000        '=>'        ',
      'COFAMV_0002'=>'        ',
      'COFAMV_0003'=>'        ',
      'AXE_0001'=>'        ',
      'AXE_0002'=>'        ',
      'AXE_0003'=>'        ',
      'AXE_0004'=>'        ',
      'ETANO'=>'        ',
      'TXTEDCODD'=>'        ',
      'TXTEDCODF'=>'        ',
      'CONTACT'=>'        ',
      'PREFBLASNO'=>'        ',
      'BLASDEPO'=>'   ',
      'TPFT'=>'1',
      'AVENANT'=>'        ',
      'PROMOTACOD'=>'        ',
      'PROMOREMCOD'=>'        ',
      'PREFCDNOPERE'=>'        ',
      'PREFPINA'=>'        ',
      'BQCPCE'=>'STR',
      'TVATIE'=>'0       ',
      'STLGTGAMCOD'=>'STD ',
      'TRANSICOD'=>'                    ',
      'TVABLCD3'=>'                    ',
      'LIEUINCT'=>'                    ',
      'ETABLNO'=>' ',
      'FRAISAPPCOD'=>'          ',
      'MODEEXP'=>'        ',
      'MOTIF'=>'        ',
     'PREFSITNO'=>'          ',
     'REMSEUILFL'=>1,
     'UNTYP'=>'        ',
     'VERSIONDEVISORIPREFPINO'=>'          ',     
     //date
     'RLVDT'=>'',
     'DELDEMDT'=>'',
     'DELACCDT'=>'',
     'DELREPDT'=>'',
     'ECHDT'=>'',
     'PIECEDT'=>NULL,
     'VALFINDT'=>NULL,   
      //number 
      'RLVNO'=>1,
      'BLASNO'=>1,
      'CESINTCOD'=>0,
      'CDNOPERE'=>0,
      'TPVBL'=>0,
      'DEEEINCCOD'=>0,
      'PINA'=>0,
      'CENOTE'=>1,
      'NOTE'=>0,
      'TXTCODD'=>1,
      'TXTCODF'=>1,
      'TXTNOTED'=>0,
      'TXTNOTEF'=>0,
      'ORIGINE'=>1,    
      'ESCP'=>0.00,
      'ACMT'=>0.00,
      'SOACMT'=>0.00,
      'REMMT'=>0.00,
      'REM1'=>0.00,
      'REMTYP1'=>1,
      'FOUHTMT'=>0.000,
      'FOUESCMT'=>0.000,
      'FOUTVAMT'=>0.000,
      'DEVP'=>1.00000000,
      'PIEDNO_0001'=>0,
      'PIEDNO_0002'=>2,
      'PIEDNO_0003'=>3,
      'PIEDMT_0001'=>0.000,
      'PIEDMT_0002'=>0.000,
      'PIEDMT_0003'=>0.000,
      'NBEX'=>1,
      'PIRELCOD'=>1,
      'RELCOD'=>2,
      'EDITCOD'=>1,
      'TRCOD'=>1,
      'BOREDICOD'=>1,
      'ASCOD'=>1,
      'ECHVCOD'=>1,
      'ENCASSCOD'=>1,
      'ADRTYP_0001'=>1,
      'ADRTYP_0002'=>1,
      'ADRTYP_0003'=>1,
      'ADRTYP_0004'=>1,
      'ADRTYP_0005'=>1,
      'PRIOCOD'=>5,
      'HTCOD'=>1,
      'STRES'=>1,
      'FAMOD'=>1,
      'PERIOD'=>1,
      'PORCOD'=>1,
      'POICOD'=>1,
      'VOLCOD'=>1,
      'PORFRFL'=>2,
      'POITOT'=>0.000,
      'VOLTOT'=>0.000,
      'COLINB'=>0,     
      'TOURRG'=>0,
      'REM_0001'=>0.00,
      'REM_0002'=>0.00,
      'REM_0003'=>0.00,
      'REMTYP_0001'=>1,
      'REMTYP_0002'=>1,
      'REMTYP_0003'=>1,
      'COMP_0001'=>0.00,
      'COMP_0002'=>0.00,
      'COMP_0003'=>0.00,
      'PORTHEOMT'=>0.00,
      'REMPIETOT'=>0.00,
      'TRANSJRNB'=>0,
      'OFASCOD'=>0,
      'FINAL'=>1,
      'QUACOD'=>2,
      'CEJOINT'=>1,
      'JOINT'=>0,
      'DEEEMT'=>0.00,
      'FOUDEEEMT'=>1,
      'PRGCDEFLG'=>1,
      'POINCOD'=>1,
      'POINTOT'=>0.000,
      'PRIOREG'=>0,
      'DTFLG'=>1,
      'SYNCHROFL'=>3,
      'ICPFL'=>1,             
      'PORFRVAL'=>0,
      'PORFRCOD'=>1,
      'CEATRAITEFL'=>0,
      'BEXNO'=>0,
      'BLQFL'=>1,
      'BPRELCOD'=>2,
      'CIRCUITVALIDATIONBLFL'=>0,
      'CIRCUITVALIDATIONFCTFL'=>0,
      'CONFIRMATIONFL'=>0,
      'SITECOD'=>'        ',
      'CATPICOD'=>'VENTE   ',
      'CONDEXP'=>'        ',               
      'GOUVFACBLQFL'=>1,
      'INDICENO'=>0,
      'SITNO'=>0,
      'TAXCPLFFL'=>1,
      'TAXSFVFL'=>1,
      'TRANSITFL'=>0,
      'TVAAUTOLIQFL'=>1,
      'UNLOGCOD'=>1,
      'UNLOGTOT'=>0.000,
      'VERSIONDEVISORIPINO'=>0,               
      'ACOMPTETYP'=>0,
      'BPJRNB'=>0,
      'PAIEMENTTYP'=>0,
      'RESJRNB'=>0,
      'STNFL'=>0,
      'BIDON'=>0,  
      'USIM_NOCAM'=>0,
      'USIM_TOT'=>0.000,
      'ULIB'=>'                                                                                                    ',
      'U_MSFODEC'=>' ',
      'U_TIMBRE'=>0,
      'U_MTTOTFODEC'=>0.000,
      'NOMPRE_AG1'=>'                                                                                ',
      'NOMPRE_AG2'=>"                                                                                ",
      'NOMPRE_C'=>"                                                                                ",
      'USIM_AG1'=>'                    ',
      'USIM_AG2'=>'                    ',
     'USIM_CHAUF'=>'                    ',
     'USIM_STAT_PL'=>0,
     'USIM_ETB_SOURCE'=>'   ',
     'USIM_NBC'=>0,
     'USIM_TRANSFERT_COMMENDE'=>0,
     'USIM_TRANSFERT_PINO'=>0,
     'USIM_TTCBC'=>0,
     'USIM_DIST'=>0,
     'USIM_PV'=>0,
     'USIM_PLAST'=>0,
     'USIM_DATBC'=>NULL,  
     //   'BTRETOURFL'=>1,
     //   'BTSTATUS'=>1,             
     //   'BTPINO'=>1,           
     'VERSIONDEVISNO'=>0,  
          
        ];
}




