<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class MOUV extends Model
{
   
    use HasFactory;
    protected $table='MOUV';
    public  $timestamps = false;
    protected $connection = 'sqlsrv';
    protected $fillable= [        
        'TIERS', 
        'REF', 
        'PREFDVNO',
        'DVNO',
        'PREFCDNO',
        'CDNO',  
        'CDQTE',        
        'DES',
        'ENRNO',//Numéro enregistrement
        'REPR_0001',      
        'PUB',  
        'CDDT' , //Date de commande
        'CDLG',//Numéro ligne de commande
        'CDSLG', //Numéro de sous-ligne en commande           
        'CDENRNO',//Identifiant ligne initiale en commande :ENRNO
        'FADT', //CURRENT DATE
        'REFAMR',//Classe de remise tarification générale
        'TACOD',//Code tarif
        'REMCOD',//Code remise
        'PUSTAT', //Prix unitaire stat. = prix unitaire en devise du dossier
        'REFQTE', //Quantité en unité référence
        'MONT', //Montant de la ligne ou total si chapitre ou poste  : REFQTE * PUSTAT
        'DECCOD' , //Code ligne décomposée non / oui
        'MVCOD',//Mise à jour du stock 1=non, 2=oui
        'PRGQTE', //??
        'GRATUITFL',//??
        'USERCR',
        'USERMO',
        'USERCRDH' , //CURRENT DATE
        'USERMODH' ,  
            
    ]; 


    protected $hidden = [
            'CE1',
           'CE2',
           'CE3',
           'CE4',
           'CE5',
           'CE6',
           'CE7',
           'CE8',
           'CE9',
           'CEA',
           'CEB',
           'CEC',
           'CED',
           'CEE',
           'CEF',           
           'SREF1',
           'SREF2',
           'TICOD',
           'PICOD',
                    
           'DVDT',
           'DVLG',
           'DVSLG',
           'DVCE4',          
           'CDDT',
           'CDLG',
           'CDSLG',
           'CDCE4',
           'CDENRNO',          
           'BLDT',
           'BLLG',
           'BLSLG',
           'BLCE4',
           'FADT',
           'FALG',
           'FASLG',
           'FACE4',
           'BPNO',
           'BPDT',
           'OP',
           
            
           'DEPO',
           'ETB',
           'PROJET',
           'MARCHE',           
           'REFFO',
           
           'REPR_0002',
           'REPR_0003',
           
           'TAFAMR',
           'TAFAMRX',
           
           'REFAMRX',
           'COFAMR',
           'COFAMV_0001',
           'COFAMV_0002',
           'COFAMV_0003',
           'DEV',
           'VENUN',
           'REFUN',
           'PUBUN',
           'EMBUN',
           'EDCOD',
           'TXTEDCOD',
           'PAGCOD',
           'PRIOCOD',
           'AXE_0001',
           'AXE_0002',
           'AXE_0003',
           'AXE_0004',
           'CPTV',
           'POSITION',
           'SENS',
           'AVENANT',
           'RELCOD_0001',
           'RELCOD_0002',
           'RELCOD_0003',
           'GAMSEQ',
           'PROMOTACOD',
           'PROMOREMCOD',
           'PUBTYP',
           'PAFORF',
           'PREFOFNO',
           'OFNO',
           
           'CDNOPERE',
           'LIGNE',
           'TICKET',
           'APPREMMT',
           'APPREMMTUN',
           'CONFIGURATEURMONOSTATUS',
           'CONFIGURATEURMULTISTATUS',
           'CONFIGURATEURLINO',
           'CONFIGURATEURREF',
           'CONFIGURATEURSREF1',
           'CONFIGURATEURSREF2',
           'USERCRDH',
           'USERMODH',
           'CENOTE',
           'NOTE',
         
           'PPAR',
           'REM_0001',
           'REM_0002',
           'REM_0003',
           'REMTYP_0001',
           'REMTYP_0002',
           'REMTYP_0003',
           'REMMT',
           'PROMOTYP',
           'PUSTAT',
           'QTE1',
           'QTE2',
           'QTE3',          
           'REFQTE',
           'EMBQTE',
           'COMP_0001',
           'COMP_0002',
           'COMP_0003',
           'COMMT_0001',
           'COMMT_0002',
           'COMMT_0003',
           'MONT',
           'FRAISMT',
           'DECCOD',
           'PCOD_0001',
           'PCOD_0002',
           'PCOD_0003',
           'PCOD_0004',
           'PCOD_0005',
           'STATUS',
           'STRES',
           'FILLERSENS',
           'MVCOD',
           'PVCOD',
           'QTETYP',
           'GADT',
           'CRTOTMT',
           'CMPTOTMT',
           'TXTCOD',
           'TXTNOTE',
           'ENRNOP_0001',
           'ENRNOP_0002',
           'ENRNOP_0003',
           'ENRNOP_0004',
           'ENRNOC_0001',
           'ENRNOC_0002',
           'ENRNOC_0003',
           'ENRNOC_0004',
           'REMPIEMT_0001',
           'REMPIEMT_0002',
           'REMPIEMT_0003',
           'REMPIEMT_0004',
           'MVSTAT',
           'BLASENRNO',
           'REMPIEPART_0001',
           'REMPIEPART_0002',
           'REMPIEPART_0003',
           'REMPIEPART_0004',
           'RECPTNO',
           'PRGQTE',
           'PRGREFQTE',
           'DVENRNO',
           'BLENRNO',
           'REBUCOD',
           'CTMFL',
           'PFCNO',
           'GPAFL',
           'ELEMNO',
           'AFRINDICE',
           'BESOINNO',
           'CONTRATCOD',
           'TVAART',
           'CADEAUFL',
           'DEPOORIG',
           'ENRNOCAD',
           'FAMONTGIM',
           'FAPUBGIM',
           'FOUFADTGIM',
           'FOUFANOGIM',
           'FOUFAQTEGIM',
           'FRAISAPPCOD',
           'FRAISFL',
           'FRAISIMPACTFLG',
           'FRAISMTGIM',
           'FRAISVALIDTYP',
           'GIMCOD',
           'GRATUITFL',
           'IAGCDENRNO',
           'ICPFL',
           'LIVDIRECTFL',
           'MOTIF',
           'OPTIONFL',
           'OPTIONVALIDEFL',
           'PANACHEFL',
           'PATOTMT',
           'PCOD_0006',
           'PRIXSPECIALFL',
           'PUNETORI',
           'REGLECOD',
           'REMCODCAD',
           'RGPENRNO',
           'SYNCHROFL',
           'TIERSEXTERNE',
           'TIERSFOU2',
           'TVANASSUJETTIEFL',
           'UNTYP',
           'BPLIGCOMPFL',
           'MOTIFSOLDE',
           'SOLDERELFL',
           'COECOD',
           'DTRENRNO',
           'DTRTYPE',
           'PERIODEDDT',
           'PERIODEFDT',  
           'UMOTIF_REC',
           'USIM_FPINO_SR',
           'USIM_TRIERS_SR',
           'UMOTIF_RETOUR',
           'UMONTPUNTTC',
           'UMONTHT',
           'U_MSPUB',
           'U_MTFODEC',
            'TTC',          
    ];

    protected $attributes=[
 
            'PREFFANO'=>'          ',
            'FANO'=>0,
            'BLNO'=>0,
            'PREFBLNO'=>'          ',
            'CE1'=>'C',
           'CE2'=>'1',
           'CE3'=>' ',
           'CE4'=>' ',
           'CE5'=>' ',
           'CE6'=>'1',
           'CE7'=>'1',
           'CE8'=>'1',
           'CE9'=>'1',
           'CEA'=>' ',
           'CEB'=>' ',
           'CEC'=>' ',
           'CED'=>' ',
           'CEE'=>' ',
           'CEF'=>' ', 
           
           'SREF1'=>'        ',
           'SREF2'=>'        ',
           'TICOD'=>'C',
           
           'DVCE4'=>' ',
           
		   'CDCE4'=>'1',
			'BLCE4'=>' ',
			'FACE4'=>' ',
			 'OP'=>'C  ',
          
           'DEPO'=>'2',
           'ETB'=>'1',
           'PROJET'=>'        ',
           'MARCHE'=>'        ',
           
           'REFFO'=>'                                        ',
          
           'REPR_0002'=>'                    ',
           'REPR_0003'=>'                    ',
         
           
        
           'TAFAMR'=>'        ',
           'TAFAMRX'=>'        ',
         
           
           'REFAMRX'=>'        ',
           'COFAMR'=>'        ',
           'COFAMV_0001'=>'        ',
           'COFAMV_0002'=>'        ',
           'COFAMV_0003'=>'        ',
           'DEV'=>'TND ',
           'VENUN'=>'PCE ',
           'REFUN'=>'PCE ',
           'PUBUN'=>'    ',
           'EMBUN'=>'    ',
           'EDCOD'=>'    ',
           'TXTEDCOD'=>'    ',
           'PAGCOD'=>'    ',
            'AXE_0001'=>'    ',
           'AXE_0002'=>'    ',
           'AXE_0003'=>'    ',
           'AXE_0004'=>'    ',
           'CPTV'=>'    ',
           'POSITION'=>'    ',
           'AVENANT'=>'    ',
            'PREFOFNO'=>'      ',
		   'GAMSEQ'=>'      ',
           'PROMOTACOD'=>'      ',
           'PROMOREMCOD'=>'      ',
              'CONFIGURATEURREF'=>'                         ',
           'CONFIGURATEURSREF1'=>'        ',
           'CONFIGURATEURSREF2'=>'        ',
           'PREFCDNOPERE'=>'      ',
           'REBUCOD'=>'    ',          
           'AFRINDICE'=>'    ',         
           'CONTRATCOD'=>'        ',
           'TVAART'=>'19',        
           'DEPOORIG'=>'   ',      
           'FOUFANOGIM'=>'                    ',
           'FRAISAPPCOD'=>'          ',     
           'GIMCOD'=>'          ',		   
           'MOTIF'=>'        ',          
           'REGLECOD'=>'        ',
           'REMCODCAD'=>'        ',          
           'TIERSEXTERNE'=>'                    ',
           'TIERSFOU2'=>'                    ',
          'MOTIFSOLDE'=>'        ',
           'UNTYP'=>'        ',
		   'COECOD'=>'    ',      
           'UMOTIF_REC' =>'                                        ',
           'USIM_FPINO_SR'=>'                    ',
           'USIM_TRIERS_SR'=>'                    ',
           'UMOTIF_RETOUR'=>'                    ',
           
           
           //numeric
           'UMONTPUNTTC'=>0.000,
           'UMONTHT'=>0.000,
           'U_MSPUB'=>0.000,
           'U_MTFODEC'=>0.000,
           'DTRTYPE'=>0,
           'TTC'=>0.000,   
            'DVLG'=>0, 
           'DVSLG'=>0, 
            
           'BLLG'=>0, 
           'BLSLG'=>0,  
           'FALG'=>0, 
           'FASLG'=>0,            
           'BPNO'=>0, 
                    
           'PRIOCOD'=>5,      
           'SENS'=>2,            
           'RELCOD_0001'=>2, 
           'RELCOD_0002'=>2, 
           'RELCOD_0003'=>2,            
           'PUBTYP'=>1, 
           'PAFORF'=>1,           
           'OFNO'=>0, 
           'CDNOPERE'=>0, 
           'LIGNE'=>0, 
           'TICKET'=>0, 
           'APPREMMT'=>0, 
           'APPREMMTUN'=>0, 
           'CONFIGURATEURMONOSTATUS'=>0, 
           'CONFIGURATEURMULTISTATUS'=>0, 
           'CONFIGURATEURLINO'=>0, 
           'CENOTE'=>1, 
           'NOTE'=>0, 
            
           'PPAR'=>0.000, 
           'REM_0001'=>0.00, 
           'REM_0002'=>0.00, 
           'REM_0003'=>0.00, 
           'REMTYP_0001'=>1, 
           'REMTYP_0002'=>1, 
           'REMTYP_0003'=>1, 
           'REMMT'=>0.000, 
           'PROMOTYP'=>1, 
           
           'QTE1'=>0.000, 
           'QTE2'=>0.000, 
           'QTE3'=>0.000, 
           'DVQTE'=>0.000,
            'BLQTE'=>0.000,
            'FAQTE'=>0.000,
           'EMBQTE'=>0.000,
           'COMP_0001'=>0.00, 
           'COMP_0002'=>0.00, 
           'COMP_0003'=>0.00, 
           'COMMT_0001'=>0.00, 
           'COMMT_0002'=>0.00, 
           'COMMT_0003'=>0.00, 
        
           'FRAISMT'=>0.00, 
           'PCOD_0001'=>4, 
           'PCOD_0002'=>4, 
           'PCOD_0003'=>2, 
           'PCOD_0004'=>2, 
           'PCOD_0005'=>2, 
           'STATUS'=>2, 
           'STRES'=>1, 
           'FILLERSENS'=>0, 
           
           'PVCOD'=>1, 
           'QTETYP'=>1, 
           'CRTOTMT'=>0.000000, 
           'CMPTOTMT'=>0.000000, 
           'TXTCOD'=>1, 
           'TXTNOTE'=>0, 
           'ENRNOP_0001'=>0, 
           'ENRNOP_0002'=>0, 
           'ENRNOP_0003'=>0, 
           'ENRNOP_0004'=>0, 
           'ENRNOC_0001'=>0, 
           'ENRNOC_0002'=>0, 
           'ENRNOC_0003'=>0, 
           'ENRNOC_0004'=>0, 
           'REMPIEMT_0001'=>0.000, 
           'REMPIEMT_0002'=>0.000, 
           'REMPIEMT_0003'=>0.000, 
           'REMPIEMT_0004'=>0.000, 
           'MVSTAT'=>1, 
           'BLASENRNO'=>0, 
           'REMPIEPART_0001'=>0.000, 
           'REMPIEPART_0002'=>0.000, 
           'REMPIEPART_0003'=>0.000, 
           'REMPIEPART_0004'=>0.000, 
           'RECPTNO'=>0, 
          
           
           'DVENRNO'=>0, 
           'BLENRNO'=>0, 
           'CTMFL'=>1, 
           'PFCNO'=>0, 
           'GPAFL'=>0, 
           'ELEMNO'=>0, 
           'BESOINNO'=>0, 
           'CADEAUFL'=>0, 
           'ENRNOCAD'=>0, 
           'FAMONTGIM'=>0.000, 
           'FAPUBGIM'=>0.000, 
           'FOUFAQTEGIM'=>0.000, 
           'FRAISFL'=>0, 
           'FRAISIMPACTFLG'=>0, 
           'FRAISMTGIM'=>0.000, 
           'FRAISVALIDTYP'=>0, 
        
           'IAGCDENRNO'=>0, 
           'ICPFL'=>1, 
           'LIVDIRECTFL'=>2, 
           'OPTIONFL'=>1, 
           'OPTIONVALIDEFL'=>1, 
           'PANACHEFL'=>1, 
           'PATOTMT'=>0.000000, 
           'PCOD_0006'=>1, 
           'PRIXSPECIALFL'=>0, 
           'PUNETORI'=>0.0000, 
           'RGPENRNO'=>0, 
           'SYNCHROFL'=>2, 
           'TVANASSUJETTIEFL'=>1, 
           'BPLIGCOMPFL'=>2,           
           'SOLDERELFL'=>0, 
		   'DTRENRNO'=>0, 
            
           //date
           'DVDT'=>NULL, 
            
		   'BLDT'=>NULL, 
           
           'BPDT'=>NULL,    
           'PERIODEDDT'=>NULL, 
           'PERIODEFDT'=>NULL, 
           'GADT'=>NULL, 
           'FOUFADTGIM'=>NULL, 
             

    ];
}
